### ISSUE TITLE
Question on content types

### ISSUE THREAD

**Issue by patrickebates** [Talegen/TalegenProjectNamiCacheLoader#1]
Curious if you are seeing any measureable performance benefits from processing static files such as .html, .js and .css.  I would have expected retrieval from "local" storage to be faster than retrieval from the blob cache.

**Comment by Talegen** [comment]
Hi Patrick. Thanks for stopping by. I honestly haven't tested but you're probably right. I will probably reduce to php, asp, and aspx. I'm using the Nami WordPress plug-in and a azure CDN so only seeing it exercised for php

**Comment by Talegen** [comment]
I've updated the code so the target file extensions are configurable. I've reduced the default to .php .aspx and .asp. Obviously will probably only ever exercise the .php with my WordPress website but I like having options.

**Comment by RobK410** [comment]
Wrapping this open item up.
